FROM rocker/geospatial:4.1.2

RUN apt-get update && apt-get -y install git

USER rstudio

RUN git clone https://github.com/heatherwander/Documents/VirginiaTech/research/BVR_GLM/bvr_glm /home/rstudio/bvr_glm

RUN Rscript /home/rstudio/bvr_glm/install.R

USER root
