### Script to look at Temperature in BVR inflows (from RC days in 2019)
### A Hounshell, 18 Jun 2020

# Load in libraries
pacman::p_load(tidyverse,ggplot2,zoo)

# Load in data: from 2025 Desktop
rc_day <- read_csv("./Raw_Data/2019_2020_continuum_data.csv")
rc_day$DateTime <- as.POSIXct(strptime(rc_day$DateTime, "%m/%d/%Y %H:%M", tz = "EST"))

bvr <- rc_day %>% filter(Reservoir == "BVR") %>% filter(Site == "B100" | Site == "B200")

fcr <- rc_day %>% filter(Reservoir == "FCR") %>% filter(Site == "F100")

# Compare to calculating stream temp from air temp (NLDAS data)
# Use equation for Herrick South stream (Sunapee) from Ward et al. 2020
# Equation was generated by comparing 2010-2013 stream temp to NLDAS air temp
nldas <- read_csv('./inputs/BVR_GLM_NLDAS_010113_123119_GMTadjusted.csv')
nldas$time = as.POSIXct(strptime(nldas$time,"%Y-%m-%d", tz="EST"))
nldas <- nldas %>% group_by(time) %>% summarize_all(funs(mean))

# Use scaling equation from Ward et al. 2020 for Herrick South Stream
nldas <- nldas %>% mutate(StreamTemp = ifelse(AirTemp >= -1.310, (1.5+(0.837*AirTemp)), 0.4))

nldas_2019 <- nldas %>% filter(time>as.POSIXct("2019-05-01")&time<as.POSIXct("2019-10-05"))

# Load in FCR 100 inflow data
temp <-read_csv("./inputs/inflow_for_EDI_2013_06Mar2020.csv")
temp$DateTime = (as.POSIXct(strptime(temp$DateTime, "%Y-%m-%d", tz="EST")))
temp <- temp %>% group_by(DateTime) %>% summarize_all(funs(mean))
temp_19 <- temp %>% group_by(DateTime) %>% summarize_all(funs(mean)) %>% filter(DateTime>as.POSIXct("2019-04-29")&DateTime<as.POSIXct("2019-10-05"))

# Plot
ggplot()+
  geom_point(bvr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_line(bvr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_point(fcr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_line(fcr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_point(nldas_2019,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_line(nldas_2019,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_point(temp_19,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  geom_line(temp_19,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  theme_classic(base_size=15)

# Plot NLDAS vs. Weir
ggplot()+
  geom_line(nldas,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_line(temp,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  theme_classic(base_size=15)


#subset weir data to days that match rc days
rc_weir_temp <- temp_19[as.Date(temp_19$DateTime) %in% as.Date(bvr$DateTime),]

#drop 6-27 because no data on this day and 6-20 + 6-22 becasue data doesn't match
rc_weir_temp <- rc_weir_temp[!(as.Date(rc_weir_temp$DateTime)=="2019-06-27" | as.Date(rc_weir_temp$DateTime)=="2019-06-20" |
                               as.Date(rc_weir_temp$DateTime)=="2019-06-22") ,]

#subset bvr to days that match weir dataset above
bvr <- bvr[as.Date(bvr$DateTime) %in% as.Date(rc_weir_temp$DateTime),]

#B100 vs weir
plot(rc_weir_temp$WVWA_Temp_C, bvr$Temp_Celcius[bvr$Site=="B100"])
b100_mod <- lm(rc_weir_temp$WVWA_Temp_C~bvr$Temp_Celcius[bvr$Site=="B100"])
abline(b100_mod, col = "red")
paste('y =', coef(b100_mod)[[2]], 'x', '+', coef(b100_mod)[[1]])

#B200 vs weir
plot(rc_weir_temp$WVWA_Temp_C, bvr$Temp_Celcius[bvr$Site=="B200"])
b200_mod <- lm(rc_weir_temp$WVWA_Temp_C~bvr$Temp_Celcius[bvr$Site=="B200"])
abline(b200_mod, col = "red")
paste('y =', coef(b200_mod)[[2]], 'x', '+', coef(b200_mod)[[1]])

#average bvr inflows
bvr_inf_avg_temp <- data.frame(DateTime = unique(as.Date(bvr$DateTime[!is.na(bvr$`Temp Sensor ID`)])),
                                   avg_temp = c(mean(bvr$Temp_Celcius[1:2]), mean(bvr$Temp_Celcius[3:4]),
                                                mean(bvr$Temp_Celcius[5:6]), mean(bvr$Temp_Celcius[7:8]),
                                                mean(bvr$Temp_Celcius[9:10])))

plot(rc_weir_temp$WVWA_Temp_C, bvr_inf_avg_temp$avg_temp)
bvr_mod <- lm(bvr_inf_avg_temp$avg_temp ~ rc_weir_temp$WVWA_Temp_C)
abline(bvr_mod, col = "red")
paste('y =', coef(bvr_mod)[[2]], 'x', '+', coef(bvr_mod)[[1]])

#find relationship between ysi temp and weir temp
plot(rc_weir_temp$WVWA_Temp_C~ fcr$Temp_Celcius[as.Date(fcr$DateTime)!= "2019-06-27"])
fcr_mod <- lm(rc_weir_temp$WVWA_Temp_C ~ fcr$Temp_Celcius[as.Date(fcr$DateTime)!= "2019-06-27"])
abline(fcr_mod, col = "red")
paste('y =', coef(fcr_mod)[[2]], 'x', '+', coef(fcr_mod)[[1]])


