### Script to look at Temperature in BVR inflows (from RC days in 2019)
### A Hounshell, 18 Jun 2020

# Load in libraries
pacman::p_load(tidyverse,ggplot2,zoo)

# Load in data: from 2025 Desktop
rc_day <- read_csv("C:/Users/ahoun/OneDrive/Desktop/BVR-GLM/BVR-GLM/Raw_Data/2019_2020_continuum_data.csv")
rc_day$DateTime <- as.POSIXct(strptime(rc_day$DateTime, "%m/%d/%Y %H:%M", tz = "EST"))

bvr <- rc_day %>% filter(Reservoir == "BVR") %>% filter(Site == "B100" | Site == "B200")

fcr <- rc_day %>% filter(Reservoir == "FCR") %>% filter(Site == "F100")

# Compare to calculating stream temp from air temp (NLDAS data)
# Use equation for Herrick South stream (Sunapee) from Ward et al. 2020
# Equation was generated by comparing 2010-2013 stream temp to NLDAS air temp
nldas <- read_csv('C:/Users/ahoun/OneDrive/Desktop/BVR-GLM/BVR-GLM/inputs/BVR_GLM_NLDAS_010113_123119_GMTadjusted.csv')
nldas$time = as.POSIXct(strptime(nldas$time,"%Y-%m-%d", tz="EST"))
nldas <- nldas %>% group_by(time) %>% summarize_all(funs(mean))

# Use scaling equation from Ward et al. 2020 for Herrick South Stream
nldas <- nldas %>% mutate(StreamTemp = ifelse(AirTemp >= -1.310, (1.5+(0.837*AirTemp)), 0.4))

nldas_2019 <- nldas %>% filter(time>as.POSIXct("2019-05-01")&time<as.POSIXct("2019-10-05"))

# Load in FCR 100 inflow data
temp <-read_csv("C:/Users/ahoun/OneDrive/Desktop/BVR-GLM/BVR-GLM/inputs/inflow_for_EDI_2013_06Mar2020.csv")
temp$DateTime = (as.POSIXct(strptime(temp$DateTime, "%Y-%m-%d", tz="EST")))
temp <- temp %>% group_by(DateTime) %>% summarize_all(funs(mean))
temp_19 <- temp %>% group_by(DateTime) %>% summarize_all(funs(mean)) %>% filter(DateTime>as.POSIXct("2019-05-01")&DateTime<as.POSIXct("2019-10-05"))

# Plot
ggplot()+
  geom_point(bvr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_line(bvr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_point(fcr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_line(fcr,mapping=aes(x=DateTime,y=Temp_Celcius,color=Site))+
  geom_point(nldas_2019,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_line(nldas_2019,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_point(temp_19,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  geom_line(temp_19,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  theme_classic(base_size=15)

# Plot NLDAS vs. Weir
ggplot()+
  geom_line(nldas,mapping=aes(x=time,y=StreamTemp,color="NLDAS"))+
  geom_line(temp,mapping=aes(x=DateTime,y=WVWA_Temp_C,color="Weir"))+
  theme_classic(base_size=15)
